### PR TITLE
NO-JIRA: Add miheer and render dev names without "rhn-support-" prefix

### PR DESCRIPTION
**Pull request by ricky-rav**
```
Rank of developers least overloaded (today) [2024-11-25]:
========================================================
#    Developer       Points    Bugs    New    Assigned    Post    Backports    SAST/ART    Total
---  ------------  --------  ------  -----  ----------  ------  -----------  ----------  -------
1    misalunk            10       1      1           0       0            0           0        1
2    npinaeva           211       4      2           2       0            0           1        5
3    mkennell           230       5      1           3       1            0           0        5
4    pepalani           730      10      3           3       4            3           0       13
5    sseethar          1023      15     11           2       2            0           1       16
6    arghosh           1210       4      0           2       2            1           0        5
7    rravaiol          1220       5      4           1       0            0           0        5
8    jluhrsen          1240       7      5           1       1            0           0        7
9    jtanenba          1420       7      7           0       0            1           0        8
10   pdiak             1602       9      4           2       3            2           0       11
11   jcaamano          2232       9      7           2       0            1           1       11
12   trozet            3322      10      5           3       2            3           0       13
---  ------------  --------  ------  -----  ----------  ------  -----------  ----------  -------
     team                        86     50          21      15           11           3      100
     external          5660      26     11           6       9            3           1       30
     sdn-team-bot       864      36     36           0       0            0           1       37
---  ------------  --------  ------  -----  ----------  ------  -----------  ----------  -------
     TOTAL                      148     97          27      24           14           5      167

```

### CODE REVIEW

**Comment by ricky-rav** [comment]
There's some problem extracting the image, but... can we just override the job?

```
[36mINFO[0m[2024-11-25T16:39:10Z] Created build "src-amd64"                    
[36mINFO[0m[2024-11-25T16:39:14Z] Build src-amd64 failed, printing logs:       
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     2  100     2    0     0     74      0 --:--:-- --:--:-- --:--:--    74
[36mINFO[0m[2024-11-25T16:39:16Z] Build src-amd64 previously failed from an infrastructure error (FetchImageContentFailed), retrying... 
[36mINFO[0m[2024-11-25T16:39:16Z] Ran for 8m37s                                
[31mERRO[0m[2024-11-25T16:39:16Z] Some steps failed:                           
[31mERRO[0m[2024-11-25T16:39:16Z] 
  * could not run steps: step src failed: error occurred handling build src-amd64: build not successful after 5 attempts: [the build src-amd64 failed after 5s with reason FetchImageContentFailed: Failed to extract image content., the build src-amd64 failed after 7s with reason FetchImageContentFailed: Failed to extract image content., the build src-amd64 failed after 6s with reason FetchImageContentFailed: Failed to extract image content.] 
[36mINFO[0m[2024-11-25T16:39:16Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:cloning_source' 
```

**Comment by tssurya** [comment]
/test images
one last try if not we override, i mean this script is not invoked in images :P but for posterity

**Pull request merged**
