### PR TITLE
SDN-4085: Enhance Troubleshooting experience with multiple DBs

### PR DESCRIPTION
**Pull request by arghosh93**
Cherry picked a commit from https://github.com/openshift/network-tools/pull/109 . The other commit on this PR has already been merged via https://github.com/openshift/network-tools/pull/101 PR and hence merging failed last time.

I added some changes to keep the usage of network-tools command similar for  both ovn-db-runlocally and ovn-dbs-run-locally.

### CODE REVIEW

**Comment by tssurya** [comment]
@arghosh93 : perhaps we can have a small demo for these changes in the upcoming weeks in the sdn team meeting to see how this works.. (not anything big just 5-10mins)

**Comment by arghosh93** [comment]
Sure :+1:

**Comment by arghosh93** [comment]
Still a valid PR. Waiting for review cycle.

**Comment by arghosh93** [comment]
Still a valid PR. Waiting for review cycle.

**Review by tssurya — APPROVED** [review]
/lgtm

**Comment by tssurya** [comment]
@arghosh93 can you show a snippet of the output from this script on the PR description when you tried it?

**Pull request merged**
