### PR TITLE
OCPBUGS-31699: replace wireshark with wireshark-cli

### PR DESCRIPTION
**Pull request by npinaeva**
wireshark was added here https://github.com/openshift/network-tools/pull/20 and only needs `tshark` to work.

### CODE REVIEW

**Comment by npinaeva** [comment]
@midu16 can you please lgtm?

**Comment by abhat** [comment]
> wireshark was added here https://github.com/openshift/network-tools/pull/20 and only needs `tshark` to work.

s/tshark/wireshark-cli

**Comment by midu16** [comment]
lgtm

thank you @npinaeva

**Pull request merged**
