### PR TITLE
SDN-4114: add packages for iptables-alerter

### PR DESCRIPTION
**Pull request by danwinship**
Adds `crictl` and `iptables`, to support the iptables-alerter (https://github.com/openshift/cluster-network-operator/pull/2329)

### CODE REVIEW

**Comment by npinaeva** [comment]
can you also update dev dockerfile https://github.com/openshift/network-tools/blob/master/Dockerfile.fedora with the new packages?

**Comment by danwinship** [comment]
Updated `Dockerfile.fedora`. Also, I removed `iptables` because it turns out that trying to filter out the ovn-k/sdn iptables rules won't actually work due to incompatibilities between versions of iptables binaries, so we'll have to just merge https://github.com/openshift/ovn-kubernetes/pull/1946 and https://github.com/openshift/sdn/pull/581

**Comment by danwinship** [comment]
hm...

>     # This image is only for development environment, so please DO NOT DEPLOY
>     # this image in any production environment.

ok, maybe I need an alternate plan

**Comment by tssurya** [comment]
> oh... actually that was from `Dockerfile.fedora`... so what is the consensus? Should we be deploying `network-tools` as a production container?

isn't it already? I thought we got some security bugs recently because it is part of payload..

**Comment by danwinship** [comment]
It's part of the payload, but (AFAIK) it's not currently used for anything that is deployed-by-default.

In my case in particular, I was going to be deploying a privileged pod using it, so that potentially opens up a bunch of holes if there was random insecure software in the image. So probably best to not do that.

> did you figure out an alternative way for crictl ?

for now I'm doing `chroot /host crictl` but I'm probably eventually going to have to build a new image anyway; we need to get an `iptables-legacy` binary so we can check for people using that too

**Pull request closed without merging**
