### PR TITLE
Add bpftrace to networking tools image

### PR DESCRIPTION
**Pull request by lazharh**
There is a need from customers and partners to debug eBPF probes on openshift clusters.
we added bcc tools and bpftrace and the related packages: there seems to be more familiarity with bpftrace rather than bcc tools.

### CODE REVIEW

**Comment by tssurya** [comment]
@lazharh : We'd like to understand why this is being added and what the motivation is and where this is planned to be used.

**Comment by lazharh** [comment]
There is a need from customers to debug eBPF probes.
This has been discussed internally with Joe.
I will discuss with him before we go ahead to merge it. I just prepared the branch

**Comment by lazharh** [comment]
@tssurya  I have updatede the PR description. Please let me know you need more context

**Comment by lazharh** [comment]
inclusive conflict resolution

**Comment by tssurya** [comment]
@lazharh : can you point us to the JIRA card for this and where the discussions happened?

**Comment by tssurya** [comment]
secondly we need someone from prod info sec security to sign off on this being a safe change to be included in this image.

**Pull request closed without merging**
